name: actions-trial
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    
    - name: チェックアウト
      uses: actions/checkout@v3
       
    - name: テストの実行
      run: |
             pwd
             tree /
             ls -altr
             cd ${{ github.workspace }}
             echo "カレントディレクトリ"
             ls -altr
             echo "ひとつ上"
             ls -altr ../
             chmod +x common_divisor_test.sh
             ./common_divisor_test.sh
