name: actions-trial
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "テストの実行"
      - run: |
             cd ${{ github.workspace }}
             chmod +x common_divisor_test.sh
             ./common_divisor_test.sh
