name: actions-trial
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "テストの実行"
      - run: |
             pwd
             tree /home/
             ls -altr
             cd ${{ github.workspace }}
             echo "カレントディレクトリ"
             ls -altr
             echo "ひとつ上"
             ls -altr ../
             chmod +x common_divisor_test.sh
             ./common_divisor_test.sh
